Subscribe to price depth updates
galtsos/trade-api-python pull request #1
Opened 2019-12-17 20:11 UTC by nevmerzhitsky

Первая версия фреймворка. Без тестов. Их добавлю позже или в другом ПР. Решил создать этот, чтобы ты мог дать обратную связь по коду, пока я делаю тесты.

Самый сложный код в `transport/`. Понять, как взаимодействуют классы, думаю, проще через анализ кода в `examples/` и далее вглубь.

2019-12-17 20:12 UTC, nevmerzhitsky commented on .dockerignore
> +.git/
Test

2019-12-18 10:24 UTC, seriousidea commented on src/galts_trade_api/exchange.py
> +    def add_market(self, market: Market):
Не хватает тайп-хинта.

2019-12-20 14:46 UTC, seriousidea requested changes

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +    Main purpose of the class is give an ability to "patch" an event loop exception handler.
Кажется, не хватает `to` перед `give`.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +async def signal_handler(signal, loop: asyncio.AbstractEventLoop):
Не хватает пары тайп-хинтов (тх).

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +async def shutdown(loop: asyncio.AbstractEventLoop):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +    print('Shutting down...')
Про принты я пока ничего не буду писать. Понимаю что в следующих коммитах ты их удалишь.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +    def exception_handler(self, loop: asyncio.AbstractEventLoop, context: Dict[str, Any]):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/exchange.py
> +    def add_market(self, market: Market):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/terminal.py
> +        event: MutableMapping[str, MutableMapping]
А почему `event`, если это не столько событие, сколько данные? Может лучше что-то типа `event_data`?

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/exchange.py
> +        id: int,
Думаю что про предупреждения IDE "shadows built-in name" упоминать не буду (кроме случаев если это может быть не безопасно). Но интересно понять почему здесь ты решил использовать `id` и проигнорировать предупреждение, а в методе `Terminal._on_init_exchange_entities_response` ты используешь `id_`?

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/tools.py
> +    def _calculate_args_hash(mcs, args, kwargs):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/__init__.py
> +    exchange: str = '*'
А почему не `exchange_tag`?

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/__init__.py
> +    def _notify(self, request: PipeRequest, data: Any) -> None:
С точки зрения самодокументируемого кода кажется что "_уведомить" - это не очень подходящее название по двум причинам:
1. Не понятно кого и о чем уведомить
2. Внутри метода происходит не уведомление потребителя, а передача ему данных

Может лучше что-то типа `pass_data_to_consumer`/`pass_response_to_consumer`?

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/__init__.py
> +    def init_response_consumer(self, request: PipeRequest) -> MessageConsumerCollection:
Не могу перевести название этого метода чтобы оценить семантику. Что именно здесь инициализируется?
- Ответ потребителя? (`init_consumer_response`)
- Ответ потребителю? (`init_response_to_consumer`)
- Коллекция потребителей?  (`init_consumer_collection_for_response`)
- etc

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/terminal.py
> +from .transport import OnExceptionCallable, TransportFactory
`OnExceptionCallable` и `Optional` не используются на данный момент.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +    ):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +        def task_done_cb(t: asyncio.Task):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +        async def loop():
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +            def task_done_cb(t: asyncio.Task):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +    async def init_exchange_entities(self, request: InitExchangeEntitiesRequest):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +class RealTransportFactoryProcess(Process):
В этом классе наверное нужно изменить порядок методов, т.к. ранее мы договаривались о том, что все приватные методы должны идти после публичных.

2019-12-20 14:46 UTC, seriousidea commented on examples/example.py
> +async def start_trade_system(program_env: AsyncProgramEnv):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on examples/example.py
> +):
Не хватает тх.

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/terminal.py
> +    async def _on_init_exchange_entities_response(
Приватные методы должны идти после всех публичных?

2019-12-20 14:46 UTC, seriousidea commented on src/galts_trade_api/transport/__init__.py
> +                raise ValueError('Pipe response message can contain exactly 2 elements')
Лучше не "может", а "должен"? То есть `can` -> `should`.

2019-12-20 16:32 UTC, nevmerzhitsky commented on src/galts_trade_api/asyncio_helper.py
> +    print('Shutting down...')
Да, планирую на логгер заменить.

2019-12-20 16:34 UTC, nevmerzhitsky commented on src/galts_trade_api/exchange.py
> +        id: int,
Это случайность, что сделал по разному в двух местах. Хоть IDE и раздражает этим предупреждением в случае `id`, лично мне хочется использовать такое имя для переменной. Хотя с другой стороны, хочется видеть 0 предупреждений в IDE. И второе, кажется, побеждает, так что заменю на `id_`.

А ты сам как считаешь?

2019-12-20 16:36 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/__init__.py
> +    def init_response_consumer(self, request: PipeRequest) -> MessageConsumerCollection:
Я имел в виду "проинициализировать получателя ответа". Подумаю позже о переименовании.

2019-12-20 16:38 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/__init__.py
> +                raise ValueError('Pipe response message can contain exactly 2 elements')
Но в случае передачи исключения используется список из одного элемента. Что думаешь?

И, кстати, для передачи исключения можно вообще не использовать список, а чисто объект исключения передавать. Что думаешь?

2019-12-20 17:47 UTC, nevmerzhitsky commented on src/galts_trade_api/exchange.py
> +        id: int,
А нет, я вспомнил. Здесь используется `id`, чтобы можно было вызывать конструктор в нотации `bla(**data)`. В `data` получается из клиента gRPC и я не хочу заменять "id" на "id_" в этом словаре перед инстанциированием. Так что я предпочту оставить код как сейчас.

2019-12-23 18:20 UTC, seriousidea commented on src/galts_trade_api/tools.py
> +    def _calculate_args_hash(mcs, args: Tuple, kwargs: Dict) -> int:
Кстати, в PEP рекомендуют для таких "контейнеров" как `args` и `kwargs` указывать не тип этого контейнера, а тип одного значения, хранящегося в нем:
https://stackoverflow.com/a/37032111

2019-12-24 22:01 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/__init__.py
> +    def _notify(self, request: PipeRequest, data: Any) -> None:
Согласен, что "уведомлять" тут не особо подходит. Переименовал переменную, этот метод, и метод в `MessageConsumerCollection`, чтобы исправить ситуацию.

Только pass здесь не подходит по смыслу. Словари говорят, что у него значение "пройти мимо", "пройти вдоль", "пройти в направлении" или "пройти сквозь". Я использовал в классе роутера "dispatch" (это типовой термин для кода про роутинг) и "send" в MessageConsumerCollection.

2019-12-24 22:08 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/__init__.py
> +    def init_response_consumer(self, request: PipeRequest) -> MessageConsumerCollection:
Переименовал в prepare_consumers_of_response

2019-12-24 22:14 UTC, nevmerzhitsky commented on src/galts_trade_api/tools.py
> +    def _calculate_args_hash(mcs, args: Tuple, kwargs: Dict) -> int:
Клевая инфа! Но в отмеченной тобой строчке у аргументом нет `*` или `**` (вместо args и kwargs может любое другое быть написано), это рядовые переменные, так что здесь это не сработает.

2019-12-24 22:16 UTC, nevmerzhitsky commented
@seriousidea я все твои комментарии обработал.

2019-12-30 16:15 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +    def _response_owner_request(self, request: PipeRequest, content: Any):
`response owner request`

Гугл сходу переводит это как "ответ владельца запроса" ( == response of request owner), что кажется очевидно не верным.

Хорошо бы устранить неоднозначность формулировки. 

Из содержимого этого метода понятно, что в названии имеется в виду "ответить владельцу запроса". В таком случае можно было бы устранить двусмысленность, например так:
`response to owner request`
Так будет более однозначно, но не на 100%, т.к. слово response - это существительное, а кажется что тут нужен глагол, то есть лучше так:
`respond to owner request`
А ещё лучше так:
`respond to request owner`
Потому что:

request owner == владелец запроса == owner of request
owner request == запрос владельца == ERROR

keyboard button == кнопка клавиатуры == button of keyboard
button keyboard == кнопочная клавиатура == ERROR

2019-12-30 16:15 UTC, seriousidea commented on src/galts_trade_api/transport/__init__.py
> +                raise ValueError('Pipe response message can contain exactly 2 elements')
> Но в случае передачи исключения используется список из одного элемента

Но эта проверка на количество элементов происходит после того, как стало точно известно что это сообщение не содержит исключение. А раз оно не содержит исключение, значит количество элементов в сообщении должно (should) быть 2.

> для передачи исключения можно вообще не использовать список

Не знаю какой вариант лучше, кажется что оба имеют как преимущества, так и недостатки, а в среднем паритет.

2019-12-30 16:22 UTC, seriousidea commented on src/galts_trade_api/tools.py
> +    def _calculate_args_hash(mcs, args: Tuple, kwargs: Dict) -> int:
Согласен. Однако, во всех остальных случаях, когда используются символы упаковки, тайп хинты отсутствуют. Значит, предлагаю указывать тайп хинты для `*args` и `**kwargs` опционально (можно указать, но не обязательно).

2019-12-30 17:07 UTC, seriousidea requested changes

2019-12-30 17:07 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +async def _cancel_tasks(loop: asyncio.AbstractEventLoop, tasks: List) -> None:
Кстати о расположении приватных методов в конце. Это правило касается только методов, но не функций?

2019-12-30 17:07 UTC, seriousidea commented on src/galts_trade_api/asyncio_helper.py
> +        - handle_signals: If None then these signals will be handled: SIGTERM, SIGINT.
Тире не нужно указывать, судя по гугловским стайлгайдам.

2020-01-03 16:00 UTC, nevmerzhitsky commented on src/galts_trade_api/asyncio_helper.py
> +async def _cancel_tasks(loop: asyncio.AbstractEventLoop, tasks: List) -> None:
Не знаю, мне кажется относительно функций не стоит такое правило добавлять.

2020-01-07 09:17 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/real.py
> +    def _response_owner_request(self, request: PipeRequest, content: Any):
Про то, что response существительное и лучше его заменить на respond to согласен, а с изменением порядка последующих слов - нет. Не понял твои последние примеры перевода: что значит ERROR?

Семантика функции в ответе на запроса процесса-владельца, поэтому это request of owner, а не owner of request. Поэтому owner request (общий подход перемещения слов при удалении "of" из фразы).

2020-01-08 18:36 UTC, seriousidea approved these changes

2020-01-08 18:37 UTC, merged