Add first tests
galtsos/trade-api-python pull request #2
Opened 2020-01-17 17:12 UTC by nevmerzhitsky

Покрыл весь код фреймворка тестами. Для простоты кода тестов добавил плагин `pytest-mock`, который позволяет использовать фикстуру `mocker` и мокать методы без контекстного менеджера.

Добавил в Docker Compose сервис для запуска `tox`, чтобы было удобнее прогонять тесты для разных окружений. И заменил его родительский образ с Alpine на Debian Buster, т.к. первое это ОС семейства MUSL, а они не соответствуют требованиям дистрибуции пакетов питона `manylinux1`. Из-за этого с PyPi скачивается версия `protobuf` без откомпилированных библиотек (и тесты падают). Заодно указал более свежие версии питона внутри `tox`.

Также переименовал несколько методов и что-то отрефакторил с целью улучшить семантику. Улучшил код проверки целостности данных в ответ на gRPC запрос `ExchangeInfo.GetEntities()`. Устранил проблему, когда один из колбеков, зарегистрированных на подписку на обновление цен мешал работе остальных, если в нём возникало исключение. Кое-где добавил код, останавливающий асинхронные подзадачи, если родительская задача была остановлена. А все прочие изменения в `src` (скорее всего) сделаны для упрощения тестирования.

2020-01-20 15:32 UTC, nevmerzhitsky commented
Отчёт по покрытию тестами:

![изображение](https://user-images.githubusercontent.com/1006042/72738688-8b499580-3bbb-11ea-844d-4c223651e7ad.png)

2020-01-27 09:27 UTC, nevmerzhitsky commented
@seriousidea когда будет ревью? :(

2020-02-01 00:42 UTC, seriousidea requested changes

2020-02-01 00:42 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +        self._exchange_info_get_entities_timeout = float(exchange_info_get_entities_timeout)
Я понимаю почему эта строчка находится именно здесь, но это нарушает "правильный" порядок инициализации атрибутов, который в идеале должен соответствовать порядку аргументов конструктора.
Но, возможно, существующий порядок атрибутов ничем не хуже и возможно даже лучше с т.з. читаемости кода.

2020-02-01 00:42 UTC, seriousidea commented on tests/terminal_test.py
> +                'id': 1,
Лучше исправить на `'id': 2`?

2020-02-01 00:42 UTC, seriousidea commented on tests/terminal_test.py
> +        assert terminal.is_exchange_entities_inited()
Похоже что эта строчка должна быть в конце теста.

2020-02-01 00:42 UTC, seriousidea commented on tests/terminal_test.py
> +        async def cb(*args):
Не хватает тх. Или, так и было задумано? Вижу что обычно ты их не указываешь для локальных функций.

2020-02-01 00:42 UTC, seriousidea commented on tests/terminal_test.py
> +    async def test_subscribe_to_prices(self):
А что будет если в методе `subscribe_to_prices()` будет баг, из-за которого не будет вызываться коллбэк? В таком случае данный тест наверное не покажет ошибку.

2020-02-01 00:42 UTC, seriousidea commented on tests/tools_test.py
> +    def test_instances_same(inst1, inst2, should_be_same):
Не хватает тх.

2020-02-01 00:42 UTC, seriousidea commented on tests/asset_test.py
> +    def test_constructor_cast_properties(self, prop: str, arg_value, expected_value):
Не хватает тх, и в тестах других сущностей и некоторых иных тестов тоже. Так и было задумано?
Вижу что обычно ты не указываешь тх для такого аргумента, у которого тип может быть разным. Для такого случая использовать `Any` разве не желательно?

2020-02-01 00:42 UTC, seriousidea commented on tests/asyncio_helper_test.py
> +    def test_setup_loop_by_arguments(self, mocker, loop_debug, handle_signals):
Не хватает тх.

2020-02-01 00:42 UTC, seriousidea commented on tests/asyncio_helper_test.py
> +    @pytest.mark.parametrize(
Можно поместить в одну строчку.

2020-02-01 00:42 UTC, seriousidea commented on tests/transport/init_test.py
> +class TestDepthConsumeKey:
Аргументы методов этого класса нет имеют тх.

2020-02-01 00:42 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +class RabbitConsumer:
В методе create_queue() этого класса лучше использовать геттер вместо атрибута `_queue`.

2020-02-01 00:42 UTC, seriousidea commented on tests/transport/real_test.py
> +            await factory.init()
А не лучше ли первый вызов `init()` разместить перед `pytest.raises`, чтобы гарантировать что исключение возникло не из-за первого вызова, а именно из-за второго? На данный момент это гарантируется лишь как побочный эффект в других тестах.

2020-02-01 00:42 UTC, seriousidea commented on tests/transport/real_test.py
> +    ):
Не хватает тх.

2020-02-01 00:42 UTC, seriousidea commented on tests/transport/real_test.py
> +    async def test_consume_price_depth(self, mocker, keys, expected_bind_exchanges):
Не хватает тх.

2020-02-01 14:58 UTC, nevmerzhitsky commented on tests/terminal_test.py
> +        assert terminal.is_exchange_entities_inited()
Ну она идёт перед следующей, чтобы минимизировать шанс исключения из следующей про таймаут. А вообще это не особо принципиально.

2020-02-01 15:08 UTC, nevmerzhitsky commented on tests/terminal_test.py
> +        async def cb(*args):
Чёт не знаю, может всё таки в таких ситуациях в них нет смысла? А именно, когда определяется локальный колбек и в теле теста видно, как он используется.

2020-02-01 15:12 UTC, nevmerzhitsky commented on tests/terminal_test.py
> +    async def test_subscribe_to_prices(self):
Всё верно! Исправил.

2020-02-01 15:38 UTC, nevmerzhitsky commented on tests/asset_test.py
> +    def test_constructor_cast_properties(self, prop: str, arg_value, expected_value):
Не было, я просто забыл об этом, как обычно.

Добавил тх в каждый тестовый метод репозитория. Про `Any` согласен, конечно.

2020-02-01 15:40 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/real.py
> +class RabbitConsumer:
Исправил.

Интересная тема, кстати. Я как-то привык в теле функции, где делается установка приватного свойства, обращаться к нему для чтения через тот же приватный интерфейс, чем использовать геттер, если он есть в классе. Но разумных причин так поступать придумать сейчас не могу.

2020-02-01 15:43 UTC, nevmerzhitsky commented on tests/transport/real_test.py
> +            await factory.init()
Однозначно лучше! Исправил.

2020-02-01 15:47 UTC, nevmerzhitsky commented on src/galts_trade_api/transport/real.py
> +        self._exchange_info_get_entities_timeout = float(exchange_info_get_entities_timeout)
В целом нет презумпции работы с аргументами конструктора в порядке их определения. Но красиво и проще, когда это так, согласен.

В этом случае изначально этот аргумент для таймаута не был опциональным, поэтому и в списке аргументов конструктора шел в том порядке, в котором он идёт в алгоритме конструктора. И если бы не опциональность, то он там бы и оставался. Думаю, в этом случае стоит оставить код как есть.

2020-02-01 15:48 UTC, nevmerzhitsky commented
@seriousidea все твои комментарии обработал.

2020-02-04 00:54 UTC, seriousidea commented on src/galts_trade_api/transport/real.py
> +        self._exchange_info_get_entities_timeout = float(exchange_info_get_entities_timeout)
Согласен.

2020-02-04 00:56 UTC, seriousidea commented on tests/terminal_test.py
> +        async def cb(*args):
Согласен конечно, особого смысла нет, но в некоторых случаях наверное было бы уместно.

2020-02-04 01:18 UTC, seriousidea commented on tests/asset_test.py
> +    def test_constructor_cast_properties(self, prop: str, arg_value, expected_value):
Гуд! А ещё пропущен тх для мокера в 6-ти тестовых методах, найти можно в поиске по шаблону "**mocker)**".
И ещё нет тх для некоторых других аргументов некоторых методов, например метод `test_constructor_cast_properties()`, но думаю что можно забить, не особо то это и существенно)

2020-02-04 01:23 UTC, seriousidea commented on tests/asyncio_helper_test.py
> +    def test_setup_loop_by_arguments(self, mocker, loop_debug, handle_signals):
Все ещё не хватает.

2020-02-04 01:58 UTC, seriousidea requested changes

2020-02-04 01:58 UTC, seriousidea commented on tests/transport/real_test.py
> +        async def cb(data): assert data == expected_response
Есть ли смысл в эту функцию добавить установку объекта Event чтобы гарантировать что функция будет вызвана?

2020-02-04 15:13 UTC, nevmerzhitsky commented on tests/asset_test.py
> +    def test_constructor_cast_properties(self, prop: str, arg_value, expected_value):
Сорри, меня IDE наебала, поэтому пропустил некоторые файлы. Всё исправил.

2020-02-04 15:35 UTC, nevmerzhitsky commented on tests/transport/real_test.py
> +        async def cb(data): assert data == expected_response
В нескольких местах исправил этот момент через `Event`.

2020-02-04 18:40 UTC, seriousidea approved these changes

2020-02-04 18:41 UTC, merged