Resolve depths update callback slowness on high updates frequence
galtsos/trade-api-python pull request #5
Opened 2020-02-21 13:13 UTC by nevmerzhitsky

Добавил механизм буферизации стаканов цен в объекте терминала, а также игнорирование колбека, установленного на событие обновления стаканов, если предыдущее обновление всё ещё обрабатывается данным колбеком.

Заодно изменил типы аргументов данного колбека - теперь все они иммутабельные (были списки, сделал кортежи).

2020-02-23 18:08 UTC, seriousidea requested changes

2020-02-23 18:08 UTC, seriousidea commented on src/galts_trade_api/terminal.py
> +        self._depths: MarketsDepthsBuffer = depths
А есть ли смысл дублировать тх в этой строке, ведь он уже указан в конструкторе для аргумента `depths`? Ну и к предыдущей строке тот же вопрос.

2020-02-23 18:08 UTC, seriousidea commented on tests/terminal_test.py
> +        with pytest.raises(ValueError, match='limit_per_market should be'):
Как насчет устранить дублирование не создавая функцию-фикстуру? Имею в виду:
`@pytest.mark.parametrize('limit', [0, -5])`

2020-02-23 18:12 UTC, nevmerzhitsky commented on src/galts_trade_api/terminal.py
> +        self._depths: MarketsDepthsBuffer = depths
Да, иначе IDE не вычислит возвращаемый тип для геттеров этих свойств и не сможет сверять тип при записи в эти приватные свойства класса (если они будут где-то кроме конструктора).

2020-02-23 19:01 UTC, seriousidea requested changes

2020-02-23 19:01 UTC, seriousidea commented on tests/terminal_test.py
> +        limit_per_market: Any
А почему `Any`, а не `int`?
И кстати, аргументы этого тестового метода легко умещаются в одну строку.

2020-02-23 19:09 UTC, seriousidea commented on src/galts_trade_api/terminal.py
> +        self._depths: MarketsDepthsBuffer = depths
Хм, я у себя проверил после удаления тх в этой строке, возвращаемый тип геттера показывает через Ctrl+Q корректно. У тебя не показывает?

2020-02-23 19:14 UTC, seriousidea commented on src/galts_trade_api/terminal.py
> +        self._depths: MarketsDepthsBuffer = depths
![изображение](https://user-images.githubusercontent.com/58702212/75118283-41f4d600-5692-11ea-8c58-9497e535c289.png)

2020-02-23 19:17 UTC, nevmerzhitsky commented on tests/terminal_test.py
> +        limit_per_market: Any
Эм, потому что мусор тоже можно передать в этом тестовом случае, очевидно.

2020-02-23 19:24 UTC, seriousidea requested changes

2020-02-23 19:24 UTC, seriousidea commented on tests/terminal_test.py
> +def fixture_constructor_exception_on_wrong_count_argument():
Эта фикстура больше не используется.

2020-02-23 20:04 UTC, seriousidea submitted a review, later dismissed

2020-02-23 22:49 UTC, nevmerzhitsky commented on src/galts_trade_api/terminal.py
> +        self._depths: MarketsDepthsBuffer = depths
Да, показывает. Видимо, IDE врубает, что если нигде точный тип не указан, то можно хотя бы из тх аргументов конструктора подцепить. Но я не думаю, что стоит на это опираться, т.к. формально если у свойства есть сеттер, то может быть отличие между тх для этого же свойства в конструкторе и в его сеттере. И это может быть даже не ошибкой.

А если у свойства класса указан точный тип во время его определения, думаю, тогда для IDE это будет более однозначной информацией и она подсветит как ворнинги те места, где указан неверный тип (в тх аргументра конструктора или сеттере).

2020-02-24 10:45 UTC, seriousidea approved these changes

2020-02-24 10:52 UTC, merged